Send Emails Locally + Space Manager Morning Report
RoboJackets/people-counter pull request #141
Opened 2020-11-24 05:21 UTC by RossIV

Send emails locally, don't relay via apiary

⚠️ .env Change Required 
- Update MAIL_* to reflect proper Mailgun configuration

Closes #128
- Add "Morning Report" sent to designated folks in each space

⚠️ Database Migration Required 
- Add "manager" attribute to space_user pivot table for ^

2020-11-24 15:48 UTC, kberzinch requested changes

2020-11-24 15:48 UTC, kberzinch commented on app/Jobs/SendSpaceManagerMorningReport.php
> +        $managers = User::whereHas('managedSpaces', static function ($q): void {
Add type hint for `$q`

2020-11-24 15:48 UTC, kberzinch commented on app/Jobs/SendSpaceManagerMorningReport.php
> +                $spacename = $space->name;
Add annotation on `Space` class for this magic property

2020-11-24 15:48 UTC, kberzinch commented on app/Notifications/PPEForm.php
> +     * @param \Illuminate\Notifications\Notifiable $notifiable
This is a trait, not a class or interface, and so cannot be used for type hints. In Apiary we're just leaving off type hints for these; you might need to adjust the analyzers to shut up about it.

2020-11-24 15:48 UTC, kberzinch commented on app/User.php
> +        return $this->belongsToMany(\App\Space::class)->withPivot('manager');
You can use relative class references here

2020-11-24 19:05 UTC, JoshOldenburg commented on resources/views/emails/spacemanagermorningreport.blade.php
> +- **{{ $visit->user->first_name }} {{ $visit->user->last_name }}** (since {{ $visit->in_time }})
It would be nice to say how long ago the visit started ("8 hours ago") if that's easy to do.

2020-11-24 19:05 UTC, JoshOldenburg commented on resources/views/emails/spacemanagermorningreport.blade.php
> +- **{{ $visit->user->first_name }} {{ $visit->user->last_name }}** (since {{ $visit->in_time }})
Should we exclude visits that started "recently", like within the previous 8 hours or so?

2020-11-26 02:07 UTC, kberzinch requested changes

2020-11-26 02:07 UTC, kberzinch commented on resources/views/emails/spacemanagermorningreport.blade.php
> +Self-service remote sign-out is available at {{ url('/') }}.
```suggestion
Your members can sign themselves out at {{ url('/') }}.
```

2020-11-26 03:10 UTC, kberzinch approved these changes

2020-11-26 04:44 UTC, JoshOldenburg approved these changes

2020-11-26 04:44 UTC, merged