Add Auditor Role
RoboJackets/people-counter pull request #83
Opened 2020-10-07 02:14 UTC by RossIV

Close #53 - Add "auditor" role with read-only access to most things

2020-10-07 03:03 UTC, kberzinch approved these changes

2020-10-08 17:58 UTC, JoshOldenburg requested changes
A few things:
- Auditors should not be allowed to update their own user (should be just restricted to `manage-users`)
- Attaching and detaching spaces from arbitrary users should be restricted to super-admins
- Auditors shouldn't be able to create personal access tokens, _especially_ for other users
- Auditors shouldn't be able to end visits for other users
- Auditors shouldn't be able to see roles and permissions at all, and especially shouldn't be able to attach/detach them from other users (see Apiary's `NovaServiceProvider` for how to restrict that)

2020-10-12 18:27 UTC, kberzinch requested changes

2020-10-12 18:27 UTC, kberzinch commented on app/Policies/VisitPolicy.php
> +    public function attachAntUser(User $user, Visit $visit)
```suggestion
    public function attachAnyUser(User $user, Visit $visit)
```

2020-10-15 02:52 UTC, JoshOldenburg requested changes
Much closer. The only remaining issue is that I have edit attached and detach buttons from users to spaces still. Every other previous issue is fixed.

2020-10-31 20:22 UTC, JoshOldenburg approved these changes

2020-10-31 20:23 UTC, merged